// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrasi/schema-engine butuh koneksi langsung (non-pooled) ke DB.
    // DIRECT_URL opsional: kalau kalian pakai pooler (Neon, Supabase, dst),
    // isi DIRECT_URL dengan connection string non-pooled di .env.
    // Tanpa pooler (kayak local dev kita), DIRECT_URL boleh kosong — fallback ke DATABASE_URL.
    url: process.env.DIRECT_URL ?? env("DATABASE_URL"),
  },
});


// Menjalankan prisma
// 1. Formatting
// 2. Validating
// 3. Migration -> ke database (generate sql)