// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
    // Catatan: `directUrl` TIDAK ada di tipe `Datasource` milik
    // @prisma/config versi 7.9.0 ini (cuma `url` & `shadowDatabaseUrl`).
    // Kalau nanti pakai pooler (Neon/Supabase) dan butuh direct connection
    // khusus buat migrate, override DATABASE_URL lewat env var saat
    // menjalankan command migrate saja, contoh:
    //   DATABASE_URL="$DIRECT_URL" bunx prisma migrate deploy
  },
});


// Menjalankan prisma
// 1. Formatting
// 2. Validating
// 3. Migration -> ke database (generate sql)